// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "BrailleKeyboardGame",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "BrailleKeyboardGame",
            targets: ["AppModule"],
            bundleIdentifier: "dev.kiattisak.BrailleKeyboard",
            teamIdentifier: "4LMZNAC89N",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .plane),
            accentColor: .presetColor(.blue),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            appCategory: .puzzleGames
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ]
)